on:
  push:
    branches:
    - main
env:
  phpVersion: 7.4
  AZURE_WEBAPP_NAME: php-testdeploy    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  PHP_VERSION: '7.4'                  # set this to the PHP version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use PHP version ${{ env.phpVersion }}
      run: |
        sudo update-alternatives --set php /usr/bin/php${{ env.phpVersion }}
        sudo update-alternatives --set phar /usr/bin/phar${{ env.phpVersion }}
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg${{ env.phpVersion }}
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi${{ env.phpVersion }}
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar${{ env.phpVersion }}
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:ondrej/php
        sudo apt update
        sudo apt install -y php7.4 php7.4-cli
        php -version
    - name: Archive files
      uses: montudor/action-zip@v0.1.0
      with:
        args: 'zip -qq -r  '
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}
                    
  deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'staging'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: php-app

        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: .
